// search action types
export const TOGGLE_DROP_DOWN = "TOGGLE_DROP_DOWN";
export const UPDATE_RECENT_TERMS = "UPDATE_RECENT_TERMS";
export const CHANGE_SEARCH_TERM = "CHANGE_SEARCH_TERM";
export const FETCH_STORES_AND_CATEGORIES = "FETCH_STORES_AND_CATEGORIES";
